jdk11 = true
ignoreRules = [ "THREAD_SAFETY_VIOLATION", "MissingSummary", "SameNameButDifferent", "NonAtomicVolatileUpdate", "EqualsGetClass"]
setup = ".lift/setup.sh"
ignoreFiles = """
skywalking-ui/**
**/target/**
/dist-material/release-docs/**
test/e2e-v2/cases/**
test/e2e-v2/java-test-service/**
"""

