version: '2.1'
services:
  skywalking-webui:
    image: sky-walking-ui:3.0.1-2017
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - skywalking-collector
    environment:
      - COLLECTOR_SERVERS=skywalking-collector:7001

  skywalking-collector:
    image: skywalking-collector:3.0.1-2017
    expose:
      - "12800"
      - "1000"
    ports:
      - "12800:12800"
    depends_on:
      es-server:
        condition: service_healthy
    links:
      - es-server
    environment:
      - ES_CLUSTER_NODES=es-server:9300
      - HTTP_HOST_NAME=0.0.0.0

  es-server:
    image: elasticsearch:5.3
    command: "-Enode.name=TestNode -Enetwork.host=0.0.0.0 -Ehttp.cors.enabled=true -Ehttp.cors.allow-origin=* -Ethread_pool.bulk.queue_size=1000 -Ecluster.name=CollectorDBCluster"
    expose:
      - "9200"
      - "9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
