# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://docs.sentry.io/server/installation/docker/#running-migrations
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-es-init"
  labels:
    app: {{ template "skywalking.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ template "skywalking.fullname" . }}-job"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-es-init"
      labels:
        app: {{ template "skywalking.name" . }}
        component: "{{ template "skywalking.fullname" . }}-job"
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      initContainers:
      {{- include "skywalking.containers.wait-for-es" . | nindent 6 }}
      containers:
      - name: {{ .Values.oap.name }}
        image: "{{ .Values.oap.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.oap.image.pullPolicy }}
{{- if .Values.oap.resources }}
        resources:
{{ toYaml .Values.oap.resources | indent 10 }}
{{- end }}
        env:
        - name: JAVA_OPTS
          value: "{{ .Values.oap.javaOpts }} -Dmode=init"
        - name: SW_STORAGE
          value: elasticsearch
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: "{{ include "call-nested" (list . "elasticsearch" "elasticsearch.client.fullname") }}:9200"
