{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasticsearch.serviceAccountName" . }}
  labels:
{{ include "elasticsearch.labels" . | nindent 4 }}
{{- end -}}
