# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: E2E

on:
  pull_request:
    # Do not run this workflow when and only when `*.md` files are modified
    paths:
      - '**'
      - '!**.md'
  push:
    branches:
      - master

env:
  SKIP_TEST: true
  SW_AGENT_JDK_VERSION: 8
  CODECOV_TOKEN: d2065307-8f01-4637-9715-2781ef096db7

jobs:
  FeatureGroup01:
    name: Feature
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        case: [auth, ssl]
    env:
      SW_SIMPLE_CASE: ${{ matrix.case }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile and Build
        run: make docker
      - name: Copy dist package
        run: cp -R dist test/e2e/
      - name: ${{ matrix.case }}
        run: ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false verify -Dit.test=org.apache.skywalking.e2e.simple.SimpleE2E
      - name: Report Coverage
        run: bash -x tools/coverage/report.sh
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs

  FeatureGroup02:
    name: Lua Nginx
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile and Build
        run: make docker
      - name: Copy dist package
        run: cp -R dist test/e2e/
      - name: Nginx Lua
        run: ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false verify -Dit.test=org.apache.skywalking.e2e.LuaE2E
      - name: Report Coverage
        run: bash -x tools/coverage/report.sh
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs

  FeatureGroup03:
    name: Gateway
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile and Build
        run: make docker
      - name: Copy dist package
        run: cp -R dist test/e2e/
      - name: Uninstrumnented gateway
        run: ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false verify -Dit.test=org.apache.skywalking.e2e.GatewayE2E
      - name: Report Coverage
        run: bash -x tools/coverage/report.sh
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs

  FeatureGroup04:
    name: Meter
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile and Build
        run: make docker
      - name: Copy dist package
        run: cp -R dist test/e2e/
      - name: Meter receiver
        run: ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false verify -Dit.test=org.apache.skywalking.e2e.meter.MeterE2E
      - name: Report Coverage
        run: bash -x tools/coverage/report.sh
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs

  FeatureGroup05:
    name: Alarm
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile and Build
        run: make docker
      - name: Copy dist package
        run: cp -R dist test/e2e/
      - name: Meter receiver
        run: ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false verify -Dit.test=org.apache.skywalking.e2e.alarm.AlarmE2E
      - name: Report Coverage
        run: bash -x tools/coverage/report.sh
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs
