# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: E2E

on:
  pull_request:
  schedule:
    - cron: '0 18 * * *'

jobs:
  JavaVersions:
    name: Agent Java Versions
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        jdk: [8, 9, 10, 11, 12, 13, 14]
    env:
      SW_SIMPLE_CASE: jdk
      SW_AGENT_JDK_VERSION: ${{ matrix.jdk }}
      SW_OAP_BASE_IMAGE: adoptopenjdk/openjdk${{ matrix.jdk }}:alpine
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          depth: 0
      - name: Set Skip Env Var
        uses: ./.github/actions/skip
      - name: Cache local Maven repository
        if: env.SKIP_CI != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set Up Java
        if: env.SKIP_CI != 'true'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Run E2E Test
        if: env.SKIP_CI != 'true'
        uses: ./.github/actions/e2e-test
        with:
          test_class: org.apache.skywalking.e2e.simple.SimpleE2E

  Single:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    needs: [JavaVersions]
    steps:
      - name: Singles Bar
        run: echo "Singles Bar - Miyuki Nakajima"
