# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: E2E

on:
  pull_request:
    # Do not run this workflow when and only when `*.md` files are modified
    paths:
      - '**'
      - '!**.md'
  schedule:
    - cron: '0 18 * * *'

env:
  SW_AGENT_JDK_VERSION: 8

jobs:
  FeatureGroup01:
    name: Feature
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        case: [auth, ssl]
    env:
      SW_SIMPLE_CASE: ${{ matrix.case }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set Skip Env Var
        uses: ./.github/actions/skip
      - name: Cache local Maven repository
        if: env.SKIP_CI != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run E2E Test
        if: env.SKIP_CI != 'true'
        uses: ./.github/actions/e2e-test
        with:
          test_class: org.apache.skywalking.e2e.simple.SimpleE2E

  FeatureGroup02:
    name: ${{ matrix.case.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        case:
          - name: Lua Nginx
            class: org.apache.skywalking.e2e.LuaE2E
          - name: Gateway
            class: org.apache.skywalking.e2e.GatewayE2E
          - name: Meter
            class: org.apache.skywalking.e2e.meter.MeterE2E
          - name: Alarm
            class: org.apache.skywalking.e2e.alarm.AlarmE2E
          - name: Zabbix
            class: org.apache.skywalking.e2e.zabbix.ZabbixE2E
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set Skip Env Var
        uses: ./.github/actions/skip
      - name: Cache local Maven repository
        if: env.SKIP_CI != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run E2E Test
        if: env.SKIP_CI != 'true'
        uses: ./.github/actions/e2e-test
        with:
          test_class: ${{ matrix.case.class }}